baseURL: "https://ilya-lesikov.com/"
googleAnalytics: "UA-157289423-1"
title: Ilya Lesikov
copyright: >
  Copyright © 2020 Ilya Lesikov. All Rights Reserved.&nbsp
  <a href="https://github.com/ilya-lesikov/ilya-lesikov.com" target="_blank">Source code</a>

languageCode: en-us
defaultContentLanguage: en-us
theme: hello-friend
enableGitInfo: true
frontmatter:
  date:
    - ":git"
    - ":default"
taxonomies:
  tag: tags

params:
  languageCode: ru-ru
  language: ru-ru
  author: Ilya Lesikov
  subtitle: Automation Developer, DevOps, SRE
  logo:
    logoText: ilya lesikov
    logoHomeLink: /
    # path: "/img/your-example-logo.svg"
    # alt: "Your example logo alt text"
  # menuMore: Show more
  # writtenBy: Written by
  # readMore: Read more
  # readOtherPosts: Read other posts
  # newerPosts: Newer posts
  # olderPosts: Older posts
  # minuteReadingTime: min read
  dateFormatSingle: "02-01-2006"
  dateFormatList: "02-01-2006"
  defaultTheme: dark
  # showMenuItems: 2
  showReadingTime: false

menu:
  main:
    # FIXME: uncomment to enable blog
    # - identifier: blog
    #   name: blog
    #   url: "/posts"
    #   weight: 10
    # - identifier: tags
    #   name: tags
    #   url: "/tags"
    #   weight: 20
    - identifier: gke-demo
      name: gke-demo
      url: "https://github.com/ilya-lesikov/gke-demo"
      pre: _blank
      weight: 30
    - identifier: resume
      name: pdf-resume
      url: "https://github.com/ilya-lesikov/resume/raw/master/resume-DevOps-Ilya-Lesikov.pdf"
      weight: 40
    - identifier: about
      name: about
      url: "/"
      weight: 50
